CC=gcc
CFLAGS=-Wall -Wextra -Werror -std=c99
CodeFiles= analysis.c BubbleStack.c Code_Assembly.c err_one_func.c expressionCommander.c parser.c symtable.c
OutputName= ifj-cc2021


.PHONY= all

all:
	$(CC) $(CFLAGS) $(CodeFiles) -o $(OutputName)

